// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: es2/common-message.proto

package es2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          MessageType            `protobuf:"varint,1,opt,name=type,proto3,enum=ES2.MessageType" json:"type,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Timestamp     uint64                 `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestHeader) Reset() {
	*x = RequestHeader{}
	mi := &file_es2_common_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestHeader) ProtoMessage() {}

func (x *RequestHeader) ProtoReflect() protoreflect.Message {
	mi := &file_es2_common_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestHeader.ProtoReflect.Descriptor instead.
func (*RequestHeader) Descriptor() ([]byte, []int) {
	return file_es2_common_message_proto_rawDescGZIP(), []int{0}
}

func (x *RequestHeader) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_Unknown
}

func (x *RequestHeader) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RequestHeader) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type ResponseHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          MessageType            `protobuf:"varint,1,opt,name=type,proto3,enum=ES2.MessageType" json:"type,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Timestamp     uint64                 `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ReturnCode    ReturnCode             `protobuf:"varint,4,opt,name=return_code,json=returnCode,proto3,enum=ES2.ReturnCode" json:"return_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseHeader) Reset() {
	*x = ResponseHeader{}
	mi := &file_es2_common_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseHeader) ProtoMessage() {}

func (x *ResponseHeader) ProtoReflect() protoreflect.Message {
	mi := &file_es2_common_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseHeader.ProtoReflect.Descriptor instead.
func (*ResponseHeader) Descriptor() ([]byte, []int) {
	return file_es2_common_message_proto_rawDescGZIP(), []int{1}
}

func (x *ResponseHeader) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_Unknown
}

func (x *ResponseHeader) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ResponseHeader) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ResponseHeader) GetReturnCode() ReturnCode {
	if x != nil {
		return x.ReturnCode
	}
	return ReturnCode_UnknownError
}

func (x *ResponseHeader) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_es2_common_message_proto protoreflect.FileDescriptor

const file_es2_common_message_proto_rawDesc = "" +
	"\n" +
	"\x18es2/common-message.proto\x12\x03ES2\x1a\x0ees2/type.proto\"c\n" +
	"\rRequestHeader\x12$\n" +
	"\x04type\x18\x01 \x01(\x0e2\x10.ES2.MessageTypeR\x04type\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x04R\ttimestamp\"\xbb\x01\n" +
	"\x0eResponseHeader\x12$\n" +
	"\x04type\x18\x01 \x01(\x0e2\x10.ES2.MessageTypeR\x04type\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x04R\ttimestamp\x120\n" +
	"\vreturn_code\x18\x04 \x01(\x0e2\x0f.ES2.ReturnCodeR\n" +
	"returnCode\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessageBGZEgithub.com/CryptoLabInc/envector-go-sdk/internal/transport/pb/es2;es2b\x06proto3"

var (
	file_es2_common_message_proto_rawDescOnce sync.Once
	file_es2_common_message_proto_rawDescData []byte
)

func file_es2_common_message_proto_rawDescGZIP() []byte {
	file_es2_common_message_proto_rawDescOnce.Do(func() {
		file_es2_common_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_es2_common_message_proto_rawDesc), len(file_es2_common_message_proto_rawDesc)))
	})
	return file_es2_common_message_proto_rawDescData
}

var file_es2_common_message_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_es2_common_message_proto_goTypes = []any{
	(*RequestHeader)(nil),  // 0: ES2.RequestHeader
	(*ResponseHeader)(nil), // 1: ES2.ResponseHeader
	(MessageType)(0),       // 2: ES2.MessageType
	(ReturnCode)(0),        // 3: ES2.ReturnCode
}
var file_es2_common_message_proto_depIdxs = []int32{
	2, // 0: ES2.RequestHeader.type:type_name -> ES2.MessageType
	2, // 1: ES2.ResponseHeader.type:type_name -> ES2.MessageType
	3, // 2: ES2.ResponseHeader.return_code:type_name -> ES2.ReturnCode
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_es2_common_message_proto_init() }
func file_es2_common_message_proto_init() {
	if File_es2_common_message_proto != nil {
		return
	}
	file_es2_type_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_es2_common_message_proto_rawDesc), len(file_es2_common_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_es2_common_message_proto_goTypes,
		DependencyIndexes: file_es2_common_message_proto_depIdxs,
		MessageInfos:      file_es2_common_message_proto_msgTypes,
	}.Build()
	File_es2_common_message_proto = out.File
	file_es2_common_message_proto_goTypes = nil
	file_es2_common_message_proto_depIdxs = nil
}
