// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: es2/type.proto

package es2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageType int32

const (
	MessageType_Unknown         MessageType = 0
	MessageType_InnerProduct    MessageType = 101
	MessageType_BatchInsertData MessageType = 111
	MessageType_RegisterKey     MessageType = 130
	MessageType_CreateIndex     MessageType = 220
	MessageType_GetIndexList    MessageType = 221
	MessageType_DeleteIndex     MessageType = 225
	MessageType_GetKeyList      MessageType = 230
	MessageType_DeleteKey       MessageType = 231
	MessageType_LoadKey         MessageType = 232
	MessageType_UnloadKey       MessageType = 233
	MessageType_GetMetadata     MessageType = 240
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0:   "Unknown",
		101: "InnerProduct",
		111: "BatchInsertData",
		130: "RegisterKey",
		220: "CreateIndex",
		221: "GetIndexList",
		225: "DeleteIndex",
		230: "GetKeyList",
		231: "DeleteKey",
		232: "LoadKey",
		233: "UnloadKey",
		240: "GetMetadata",
	}
	MessageType_value = map[string]int32{
		"Unknown":         0,
		"InnerProduct":    101,
		"BatchInsertData": 111,
		"RegisterKey":     130,
		"CreateIndex":     220,
		"GetIndexList":    221,
		"DeleteIndex":     225,
		"GetKeyList":      230,
		"DeleteKey":       231,
		"LoadKey":         232,
		"UnloadKey":       233,
		"GetMetadata":     240,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_es2_type_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_es2_type_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_es2_type_proto_rawDescGZIP(), []int{0}
}

type IndexType int32

const (
	IndexType_HE_FLAT IndexType = 0
	IndexType_FLAT    IndexType = 2
)

// Enum value maps for IndexType.
var (
	IndexType_name = map[int32]string{
		0: "HE_FLAT",
		2: "FLAT",
	}
	IndexType_value = map[string]int32{
		"HE_FLAT": 0,
		"FLAT":    2,
	}
)

func (x IndexType) Enum() *IndexType {
	p := new(IndexType)
	*p = x
	return p
}

func (x IndexType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IndexType) Descriptor() protoreflect.EnumDescriptor {
	return file_es2_type_proto_enumTypes[1].Descriptor()
}

func (IndexType) Type() protoreflect.EnumType {
	return &file_es2_type_proto_enumTypes[1]
}

func (x IndexType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IndexType.Descriptor instead.
func (IndexType) EnumDescriptor() ([]byte, []int) {
	return file_es2_type_proto_rawDescGZIP(), []int{1}
}

type SearchType int32

const (
	SearchType_IPOnly SearchType = 0
)

// Enum value maps for SearchType.
var (
	SearchType_name = map[int32]string{
		0: "IPOnly",
	}
	SearchType_value = map[string]int32{
		"IPOnly": 0,
	}
)

func (x SearchType) Enum() *SearchType {
	p := new(SearchType)
	*p = x
	return p
}

func (x SearchType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SearchType) Descriptor() protoreflect.EnumDescriptor {
	return file_es2_type_proto_enumTypes[2].Descriptor()
}

func (SearchType) Type() protoreflect.EnumType {
	return &file_es2_type_proto_enumTypes[2]
}

func (x SearchType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SearchType.Descriptor instead.
func (SearchType) EnumDescriptor() ([]byte, []int) {
	return file_es2_type_proto_rawDescGZIP(), []int{2}
}

type ReturnCode int32

const (
	ReturnCode_UnknownError          ReturnCode = 0
	ReturnCode_Success               ReturnCode = 1
	ReturnCode_Fail                  ReturnCode = 2
	ReturnCode_NoSuchIndex           ReturnCode = 3
	ReturnCode_InvalidInput          ReturnCode = 4
	ReturnCode_NotFoundError         ReturnCode = 5
	ReturnCode_InvalidKeyURL         ReturnCode = 6
	ReturnCode_InvalidKeyAuthInfo    ReturnCode = 7
	ReturnCode_FailedToUnpackKey     ReturnCode = 8
	ReturnCode_InsufficientDIskSpace ReturnCode = 9
	ReturnCode_Warning               ReturnCode = 10
)

// Enum value maps for ReturnCode.
var (
	ReturnCode_name = map[int32]string{
		0:  "UnknownError",
		1:  "Success",
		2:  "Fail",
		3:  "NoSuchIndex",
		4:  "InvalidInput",
		5:  "NotFoundError",
		6:  "InvalidKeyURL",
		7:  "InvalidKeyAuthInfo",
		8:  "FailedToUnpackKey",
		9:  "InsufficientDIskSpace",
		10: "Warning",
	}
	ReturnCode_value = map[string]int32{
		"UnknownError":          0,
		"Success":               1,
		"Fail":                  2,
		"NoSuchIndex":           3,
		"InvalidInput":          4,
		"NotFoundError":         5,
		"InvalidKeyURL":         6,
		"InvalidKeyAuthInfo":    7,
		"FailedToUnpackKey":     8,
		"InsufficientDIskSpace": 9,
		"Warning":               10,
	}
)

func (x ReturnCode) Enum() *ReturnCode {
	p := new(ReturnCode)
	*p = x
	return p
}

func (x ReturnCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReturnCode) Descriptor() protoreflect.EnumDescriptor {
	return file_es2_type_proto_enumTypes[3].Descriptor()
}

func (ReturnCode) Type() protoreflect.EnumType {
	return &file_es2_type_proto_enumTypes[3]
}

func (x ReturnCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReturnCode.Descriptor instead.
func (ReturnCode) EnumDescriptor() ([]byte, []int) {
	return file_es2_type_proto_rawDescGZIP(), []int{3}
}

type Vector struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Dim           uint64                 `protobuf:"varint,2,opt,name=dim,proto3" json:"dim,omitempty"`
	Level         uint64                 `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`
	Data          []float32              `protobuf:"fixed32,4,rep,packed,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vector) Reset() {
	*x = Vector{}
	mi := &file_es2_type_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vector) ProtoMessage() {}

func (x *Vector) ProtoReflect() protoreflect.Message {
	mi := &file_es2_type_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vector.ProtoReflect.Descriptor instead.
func (*Vector) Descriptor() ([]byte, []int) {
	return file_es2_type_proto_rawDescGZIP(), []int{0}
}

func (x *Vector) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Vector) GetDim() uint64 {
	if x != nil {
		return x.Dim
	}
	return 0
}

func (x *Vector) GetLevel() uint64 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *Vector) GetData() []float32 {
	if x != nil {
		return x.Data
	}
	return nil
}

type PackedCiphertexts struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PackedCiphertexts) Reset() {
	*x = PackedCiphertexts{}
	mi := &file_es2_type_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackedCiphertexts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackedCiphertexts) ProtoMessage() {}

func (x *PackedCiphertexts) ProtoReflect() protoreflect.Message {
	mi := &file_es2_type_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackedCiphertexts.ProtoReflect.Descriptor instead.
func (*PackedCiphertexts) Descriptor() ([]byte, []int) {
	return file_es2_type_proto_rawDescGZIP(), []int{1}
}

func (x *PackedCiphertexts) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PackedCiphertexts) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type HEaaNCiphertext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Degree        uint64                 `protobuf:"varint,1,opt,name=degree,proto3" json:"degree,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HEaaNCiphertext) Reset() {
	*x = HEaaNCiphertext{}
	mi := &file_es2_type_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HEaaNCiphertext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HEaaNCiphertext) ProtoMessage() {}

func (x *HEaaNCiphertext) ProtoReflect() protoreflect.Message {
	mi := &file_es2_type_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HEaaNCiphertext.ProtoReflect.Descriptor instead.
func (*HEaaNCiphertext) Descriptor() ([]byte, []int) {
	return file_es2_type_proto_rawDescGZIP(), []int{2}
}

func (x *HEaaNCiphertext) GetDegree() uint64 {
	if x != nil {
		return x.Degree
	}
	return 0
}

func (x *HEaaNCiphertext) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type DataType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlainVector   *Vector                `protobuf:"bytes,1,opt,name=plain_vector,json=plainVector,proto3" json:"plain_vector,omitempty"`
	CipherVector  *PackedCiphertexts     `protobuf:"bytes,2,opt,name=cipher_vector,json=cipherVector,proto3" json:"cipher_vector,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataType) Reset() {
	*x = DataType{}
	mi := &file_es2_type_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataType) ProtoMessage() {}

func (x *DataType) ProtoReflect() protoreflect.Message {
	mi := &file_es2_type_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataType.ProtoReflect.Descriptor instead.
func (*DataType) Descriptor() ([]byte, []int) {
	return file_es2_type_proto_rawDescGZIP(), []int{3}
}

func (x *DataType) GetPlainVector() *Vector {
	if x != nil {
		return x.PlainVector
	}
	return nil
}

func (x *DataType) GetCipherVector() *PackedCiphertexts {
	if x != nil {
		return x.CipherVector
	}
	return nil
}

type MetadataIdx struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShardIdx      uint64                 `protobuf:"varint,1,opt,name=shard_idx,json=shardIdx,proto3" json:"shard_idx,omitempty"`
	RowIdx        uint64                 `protobuf:"varint,2,opt,name=row_idx,json=rowIdx,proto3" json:"row_idx,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataIdx) Reset() {
	*x = MetadataIdx{}
	mi := &file_es2_type_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataIdx) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataIdx) ProtoMessage() {}

func (x *MetadataIdx) ProtoReflect() protoreflect.Message {
	mi := &file_es2_type_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataIdx.ProtoReflect.Descriptor instead.
func (*MetadataIdx) Descriptor() ([]byte, []int) {
	return file_es2_type_proto_rawDescGZIP(), []int{4}
}

func (x *MetadataIdx) GetShardIdx() uint64 {
	if x != nil {
		return x.ShardIdx
	}
	return 0
}

func (x *MetadataIdx) GetRowIdx() uint64 {
	if x != nil {
		return x.RowIdx
	}
	return 0
}

type PackedVectors struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vector        *DataType              `protobuf:"bytes,1,opt,name=vector,proto3" json:"vector,omitempty"`
	Metadata      []string               `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty"`
	NumVector     uint64                 `protobuf:"varint,3,opt,name=num_vector,json=numVector,proto3" json:"num_vector,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PackedVectors) Reset() {
	*x = PackedVectors{}
	mi := &file_es2_type_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackedVectors) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackedVectors) ProtoMessage() {}

func (x *PackedVectors) ProtoReflect() protoreflect.Message {
	mi := &file_es2_type_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackedVectors.ProtoReflect.Descriptor instead.
func (*PackedVectors) Descriptor() ([]byte, []int) {
	return file_es2_type_proto_rawDescGZIP(), []int{5}
}

func (x *PackedVectors) GetVector() *DataType {
	if x != nil {
		return x.Vector
	}
	return nil
}

func (x *PackedVectors) GetMetadata() []string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *PackedVectors) GetNumVector() uint64 {
	if x != nil {
		return x.NumVector
	}
	return 0
}

type CiphertextScore struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ShardIdx      []uint64               `protobuf:"varint,2,rep,packed,name=shard_idx,json=shardIdx,proto3" json:"shard_idx,omitempty"`
	CtxtScore     []*HEaaNCiphertext     `protobuf:"bytes,3,rep,name=ctxt_score,json=ctxtScore,proto3" json:"ctxt_score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CiphertextScore) Reset() {
	*x = CiphertextScore{}
	mi := &file_es2_type_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CiphertextScore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CiphertextScore) ProtoMessage() {}

func (x *CiphertextScore) ProtoReflect() protoreflect.Message {
	mi := &file_es2_type_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CiphertextScore.ProtoReflect.Descriptor instead.
func (*CiphertextScore) Descriptor() ([]byte, []int) {
	return file_es2_type_proto_rawDescGZIP(), []int{6}
}

func (x *CiphertextScore) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CiphertextScore) GetShardIdx() []uint64 {
	if x != nil {
		return x.ShardIdx
	}
	return nil
}

func (x *CiphertextScore) GetCtxtScore() []*HEaaNCiphertext {
	if x != nil {
		return x.CtxtScore
	}
	return nil
}

type Metadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Data          string                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_es2_type_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_es2_type_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_es2_type_proto_rawDescGZIP(), []int{7}
}

func (x *Metadata) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Metadata) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type Key struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Size          uint64                 `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Key) Reset() {
	*x = Key{}
	mi := &file_es2_type_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Key) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Key) ProtoMessage() {}

func (x *Key) ProtoReflect() protoreflect.Message {
	mi := &file_es2_type_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Key.ProtoReflect.Descriptor instead.
func (*Key) Descriptor() ([]byte, []int) {
	return file_es2_type_proto_rawDescGZIP(), []int{8}
}

func (x *Key) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Key) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type KeyInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyId         string                 `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Preset        string                 `protobuf:"bytes,3,opt,name=preset,proto3" json:"preset,omitempty"`
	EvalMode      string                 `protobuf:"bytes,4,opt,name=eval_mode,json=evalMode,proto3" json:"eval_mode,omitempty"`
	Sha256Sum     string                 `protobuf:"bytes,5,opt,name=sha256sum,proto3" json:"sha256sum,omitempty"`
	IsLoaded      bool                   `protobuf:"varint,6,opt,name=is_loaded,json=isLoaded,proto3" json:"is_loaded,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyInfo) Reset() {
	*x = KeyInfo{}
	mi := &file_es2_type_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyInfo) ProtoMessage() {}

func (x *KeyInfo) ProtoReflect() protoreflect.Message {
	mi := &file_es2_type_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyInfo.ProtoReflect.Descriptor instead.
func (*KeyInfo) Descriptor() ([]byte, []int) {
	return file_es2_type_proto_rawDescGZIP(), []int{9}
}

func (x *KeyInfo) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *KeyInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *KeyInfo) GetPreset() string {
	if x != nil {
		return x.Preset
	}
	return ""
}

func (x *KeyInfo) GetEvalMode() string {
	if x != nil {
		return x.EvalMode
	}
	return ""
}

func (x *KeyInfo) GetSha256Sum() string {
	if x != nil {
		return x.Sha256Sum
	}
	return ""
}

func (x *KeyInfo) GetIsLoaded() bool {
	if x != nil {
		return x.IsLoaded
	}
	return false
}

// Field 11 (index_detail) is reserved for IVF configuration, unsupported here.
type IndexInfo struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	IndexName          string                 `protobuf:"bytes,1,opt,name=index_name,json=indexName,proto3" json:"index_name,omitempty"`
	Dim                uint64                 `protobuf:"varint,2,opt,name=dim,proto3" json:"dim,omitempty"`
	RowCount           uint64                 `protobuf:"varint,3,opt,name=row_count,json=rowCount,proto3" json:"row_count,omitempty"`
	SearchType         SearchType             `protobuf:"varint,4,opt,name=search_type,json=searchType,proto3,enum=ES2.SearchType" json:"search_type,omitempty"`
	KeyId              string                 `protobuf:"bytes,5,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	IndexEncryption    string                 `protobuf:"bytes,6,opt,name=index_encryption,json=indexEncryption,proto3" json:"index_encryption,omitempty"`
	QueryEncryption    string                 `protobuf:"bytes,7,opt,name=query_encryption,json=queryEncryption,proto3" json:"query_encryption,omitempty"`
	CreatedTime        string                 `protobuf:"bytes,8,opt,name=created_time,json=createdTime,proto3" json:"created_time,omitempty"`
	IndexType          IndexType              `protobuf:"varint,9,opt,name=index_type,json=indexType,proto3,enum=ES2.IndexType" json:"index_type,omitempty"`
	IsLoaded           bool                   `protobuf:"varint,10,opt,name=is_loaded,json=isLoaded,proto3" json:"is_loaded,omitempty"`
	IsKeyLoaded        bool                   `protobuf:"varint,12,opt,name=is_key_loaded,json=isKeyLoaded,proto3" json:"is_key_loaded,omitempty"`
	MetadataEncryption bool                   `protobuf:"varint,13,opt,name=metadata_encryption,json=metadataEncryption,proto3" json:"metadata_encryption,omitempty"`
	Description        string                 `protobuf:"bytes,14,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *IndexInfo) Reset() {
	*x = IndexInfo{}
	mi := &file_es2_type_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexInfo) ProtoMessage() {}

func (x *IndexInfo) ProtoReflect() protoreflect.Message {
	mi := &file_es2_type_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexInfo.ProtoReflect.Descriptor instead.
func (*IndexInfo) Descriptor() ([]byte, []int) {
	return file_es2_type_proto_rawDescGZIP(), []int{10}
}

func (x *IndexInfo) GetIndexName() string {
	if x != nil {
		return x.IndexName
	}
	return ""
}

func (x *IndexInfo) GetDim() uint64 {
	if x != nil {
		return x.Dim
	}
	return 0
}

func (x *IndexInfo) GetRowCount() uint64 {
	if x != nil {
		return x.RowCount
	}
	return 0
}

func (x *IndexInfo) GetSearchType() SearchType {
	if x != nil {
		return x.SearchType
	}
	return SearchType_IPOnly
}

func (x *IndexInfo) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *IndexInfo) GetIndexEncryption() string {
	if x != nil {
		return x.IndexEncryption
	}
	return ""
}

func (x *IndexInfo) GetQueryEncryption() string {
	if x != nil {
		return x.QueryEncryption
	}
	return ""
}

func (x *IndexInfo) GetCreatedTime() string {
	if x != nil {
		return x.CreatedTime
	}
	return ""
}

func (x *IndexInfo) GetIndexType() IndexType {
	if x != nil {
		return x.IndexType
	}
	return IndexType_HE_FLAT
}

func (x *IndexInfo) GetIsLoaded() bool {
	if x != nil {
		return x.IsLoaded
	}
	return false
}

func (x *IndexInfo) GetIsKeyLoaded() bool {
	if x != nil {
		return x.IsKeyLoaded
	}
	return false
}

func (x *IndexInfo) GetMetadataEncryption() bool {
	if x != nil {
		return x.MetadataEncryption
	}
	return false
}

func (x *IndexInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_es2_type_proto protoreflect.FileDescriptor

const file_es2_type_proto_rawDesc = "" +
	"\n" +
	"\x0ees2/type.proto\x12\x03ES2\"T\n" +
	"\x06Vector\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03dim\x18\x02 \x01(\x04R\x03dim\x12\x14\n" +
	"\x05level\x18\x03 \x01(\x04R\x05level\x12\x12\n" +
	"\x04data\x18\x04 \x03(\x02R\x04data\"7\n" +
	"\x11PackedCiphertexts\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"=\n" +
	"\x0fHEaaNCiphertext\x12\x16\n" +
	"\x06degree\x18\x01 \x01(\x04R\x06degree\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"w\n" +
	"\bDataType\x12.\n" +
	"\fplain_vector\x18\x01 \x01(\v2\v.ES2.VectorR\vplainVector\x12;\n" +
	"\rcipher_vector\x18\x02 \x01(\v2\x16.ES2.PackedCiphertextsR\fcipherVector\"C\n" +
	"\vMetadataIdx\x12\x1b\n" +
	"\tshard_idx\x18\x01 \x01(\x04R\bshardIdx\x12\x17\n" +
	"\arow_idx\x18\x02 \x01(\x04R\x06rowIdx\"q\n" +
	"\rPackedVectors\x12%\n" +
	"\x06vector\x18\x01 \x01(\v2\r.ES2.DataTypeR\x06vector\x12\x1a\n" +
	"\bmetadata\x18\x02 \x03(\tR\bmetadata\x12\x1d\n" +
	"\n" +
	"num_vector\x18\x03 \x01(\x04R\tnumVector\"s\n" +
	"\x0fCiphertextScore\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tshard_idx\x18\x02 \x03(\x04R\bshardIdx\x123\n" +
	"\n" +
	"ctxt_score\x18\x03 \x03(\v2\x14.ES2.HEaaNCiphertextR\tctxtScore\".\n" +
	"\bMetadata\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04data\x18\x02 \x01(\tR\x04data\"/\n" +
	"\x03Key\x12\x12\n" +
	"\x04size\x18\x01 \x01(\x04R\x04size\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"\xa4\x01\n" +
	"\aKeyInfo\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x16\n" +
	"\x06preset\x18\x03 \x01(\tR\x06preset\x12\x1b\n" +
	"\teval_mode\x18\x04 \x01(\tR\bevalMode\x12\x1c\n" +
	"\tsha256sum\x18\x05 \x01(\tR\tsha256sum\x12\x1b\n" +
	"\tis_loaded\x18\x06 \x01(\bR\bisLoaded\"\xde\x03\n" +
	"\tIndexInfo\x12\x1d\n" +
	"\n" +
	"index_name\x18\x01 \x01(\tR\tindexName\x12\x10\n" +
	"\x03dim\x18\x02 \x01(\x04R\x03dim\x12\x1b\n" +
	"\trow_count\x18\x03 \x01(\x04R\browCount\x120\n" +
	"\vsearch_type\x18\x04 \x01(\x0e2\x0f.ES2.SearchTypeR\n" +
	"searchType\x12\x15\n" +
	"\x06key_id\x18\x05 \x01(\tR\x05keyId\x12)\n" +
	"\x10index_encryption\x18\x06 \x01(\tR\x0findexEncryption\x12)\n" +
	"\x10query_encryption\x18\a \x01(\tR\x0fqueryEncryption\x12!\n" +
	"\fcreated_time\x18\b \x01(\tR\vcreatedTime\x12-\n" +
	"\n" +
	"index_type\x18\t \x01(\x0e2\x0e.ES2.IndexTypeR\tindexType\x12\x1b\n" +
	"\tis_loaded\x18\n" +
	" \x01(\bR\bisLoaded\x12\"\n" +
	"\ris_key_loaded\x18\f \x01(\bR\visKeyLoaded\x12/\n" +
	"\x13metadata_encryption\x18\r \x01(\bR\x12metadataEncryption\x12 \n" +
	"\vdescription\x18\x0e \x01(\tR\vdescription*\xdb\x01\n" +
	"\vMessageType\x12\v\n" +
	"\aUnknown\x10\x00\x12\x10\n" +
	"\fInnerProduct\x10e\x12\x13\n" +
	"\x0fBatchInsertData\x10o\x12\x10\n" +
	"\vRegisterKey\x10\x82\x01\x12\x10\n" +
	"\vCreateIndex\x10\xdc\x01\x12\x11\n" +
	"\fGetIndexList\x10\xdd\x01\x12\x10\n" +
	"\vDeleteIndex\x10\xe1\x01\x12\x0f\n" +
	"\n" +
	"GetKeyList\x10\xe6\x01\x12\x0e\n" +
	"\tDeleteKey\x10\xe7\x01\x12\f\n" +
	"\aLoadKey\x10\xe8\x01\x12\x0e\n" +
	"\tUnloadKey\x10\xe9\x01\x12\x10\n" +
	"\vGetMetadata\x10\xf0\x01*\"\n" +
	"\tIndexType\x12\v\n" +
	"\aHE_FLAT\x10\x00\x12\b\n" +
	"\x04FLAT\x10\x02*\x18\n" +
	"\n" +
	"SearchType\x12\n" +
	"\n" +
	"\x06IPOnly\x10\x00*\xd5\x01\n" +
	"\n" +
	"ReturnCode\x12\x10\n" +
	"\fUnknownError\x10\x00\x12\v\n" +
	"\aSuccess\x10\x01\x12\b\n" +
	"\x04Fail\x10\x02\x12\x0f\n" +
	"\vNoSuchIndex\x10\x03\x12\x10\n" +
	"\fInvalidInput\x10\x04\x12\x11\n" +
	"\rNotFoundError\x10\x05\x12\x11\n" +
	"\rInvalidKeyURL\x10\x06\x12\x16\n" +
	"\x12InvalidKeyAuthInfo\x10\a\x12\x15\n" +
	"\x11FailedToUnpackKey\x10\b\x12\x19\n" +
	"\x15InsufficientDIskSpace\x10\t\x12\v\n" +
	"\aWarning\x10\n" +
	"BGZEgithub.com/CryptoLabInc/envector-go-sdk/internal/transport/pb/es2;es2b\x06proto3"

var (
	file_es2_type_proto_rawDescOnce sync.Once
	file_es2_type_proto_rawDescData []byte
)

func file_es2_type_proto_rawDescGZIP() []byte {
	file_es2_type_proto_rawDescOnce.Do(func() {
		file_es2_type_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_es2_type_proto_rawDesc), len(file_es2_type_proto_rawDesc)))
	})
	return file_es2_type_proto_rawDescData
}

var file_es2_type_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_es2_type_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_es2_type_proto_goTypes = []any{
	(MessageType)(0),          // 0: ES2.MessageType
	(IndexType)(0),            // 1: ES2.IndexType
	(SearchType)(0),           // 2: ES2.SearchType
	(ReturnCode)(0),           // 3: ES2.ReturnCode
	(*Vector)(nil),            // 4: ES2.Vector
	(*PackedCiphertexts)(nil), // 5: ES2.PackedCiphertexts
	(*HEaaNCiphertext)(nil),   // 6: ES2.HEaaNCiphertext
	(*DataType)(nil),          // 7: ES2.DataType
	(*MetadataIdx)(nil),       // 8: ES2.MetadataIdx
	(*PackedVectors)(nil),     // 9: ES2.PackedVectors
	(*CiphertextScore)(nil),   // 10: ES2.CiphertextScore
	(*Metadata)(nil),          // 11: ES2.Metadata
	(*Key)(nil),               // 12: ES2.Key
	(*KeyInfo)(nil),           // 13: ES2.KeyInfo
	(*IndexInfo)(nil),         // 14: ES2.IndexInfo
}
var file_es2_type_proto_depIdxs = []int32{
	4, // 0: ES2.DataType.plain_vector:type_name -> ES2.Vector
	5, // 1: ES2.DataType.cipher_vector:type_name -> ES2.PackedCiphertexts
	7, // 2: ES2.PackedVectors.vector:type_name -> ES2.DataType
	6, // 3: ES2.CiphertextScore.ctxt_score:type_name -> ES2.HEaaNCiphertext
	2, // 4: ES2.IndexInfo.search_type:type_name -> ES2.SearchType
	1, // 5: ES2.IndexInfo.index_type:type_name -> ES2.IndexType
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_es2_type_proto_init() }
func file_es2_type_proto_init() {
	if File_es2_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_es2_type_proto_rawDesc), len(file_es2_type_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_es2_type_proto_goTypes,
		DependencyIndexes: file_es2_type_proto_depIdxs,
		EnumInfos:         file_es2_type_proto_enumTypes,
		MessageInfos:      file_es2_type_proto_msgTypes,
	}.Build()
	File_es2_type_proto = out.File
	file_es2_type_proto_goTypes = nil
	file_es2_type_proto_depIdxs = nil
}
