// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: es2e/es2e-message.proto

package es2e

import (
	es2 "github.com/CryptoLabInc/envector-go-sdk/internal/transport/pb/es2"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetIndexListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *es2.RequestHeader     `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	LoadedOnly    bool                   `protobuf:"varint,2,opt,name=loaded_only,json=loadedOnly,proto3" json:"loaded_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIndexListRequest) Reset() {
	*x = GetIndexListRequest{}
	mi := &file_es2e_es2e_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIndexListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIndexListRequest) ProtoMessage() {}

func (x *GetIndexListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_es2e_es2e_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIndexListRequest.ProtoReflect.Descriptor instead.
func (*GetIndexListRequest) Descriptor() ([]byte, []int) {
	return file_es2e_es2e_message_proto_rawDescGZIP(), []int{0}
}

func (x *GetIndexListRequest) GetHeader() *es2.RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *GetIndexListRequest) GetLoadedOnly() bool {
	if x != nil {
		return x.LoadedOnly
	}
	return false
}

type GetIndexListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *es2.ResponseHeader    `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	IndexNames    []string               `protobuf:"bytes,2,rep,name=index_names,json=indexNames,proto3" json:"index_names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIndexListResponse) Reset() {
	*x = GetIndexListResponse{}
	mi := &file_es2e_es2e_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIndexListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIndexListResponse) ProtoMessage() {}

func (x *GetIndexListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_es2e_es2e_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIndexListResponse.ProtoReflect.Descriptor instead.
func (*GetIndexListResponse) Descriptor() ([]byte, []int) {
	return file_es2e_es2e_message_proto_rawDescGZIP(), []int{1}
}

func (x *GetIndexListResponse) GetHeader() *es2.ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *GetIndexListResponse) GetIndexNames() []string {
	if x != nil {
		return x.IndexNames
	}
	return nil
}

type BatchInsertDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *es2.RequestHeader     `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	IndexName     string                 `protobuf:"bytes,2,opt,name=index_name,json=indexName,proto3" json:"index_name,omitempty"`
	PackedVectors []*es2.PackedVectors   `protobuf:"bytes,3,rep,name=packed_vectors,json=packedVectors,proto3" json:"packed_vectors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchInsertDataRequest) Reset() {
	*x = BatchInsertDataRequest{}
	mi := &file_es2e_es2e_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchInsertDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchInsertDataRequest) ProtoMessage() {}

func (x *BatchInsertDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_es2e_es2e_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchInsertDataRequest.ProtoReflect.Descriptor instead.
func (*BatchInsertDataRequest) Descriptor() ([]byte, []int) {
	return file_es2e_es2e_message_proto_rawDescGZIP(), []int{2}
}

func (x *BatchInsertDataRequest) GetHeader() *es2.RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *BatchInsertDataRequest) GetIndexName() string {
	if x != nil {
		return x.IndexName
	}
	return ""
}

func (x *BatchInsertDataRequest) GetPackedVectors() []*es2.PackedVectors {
	if x != nil {
		return x.PackedVectors
	}
	return nil
}

type BatchInsertDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *es2.ResponseHeader    `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	ItemIds       []int64                `protobuf:"varint,2,rep,packed,name=item_ids,json=itemIds,proto3" json:"item_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchInsertDataResponse) Reset() {
	*x = BatchInsertDataResponse{}
	mi := &file_es2e_es2e_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchInsertDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchInsertDataResponse) ProtoMessage() {}

func (x *BatchInsertDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_es2e_es2e_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchInsertDataResponse.ProtoReflect.Descriptor instead.
func (*BatchInsertDataResponse) Descriptor() ([]byte, []int) {
	return file_es2e_es2e_message_proto_rawDescGZIP(), []int{3}
}

func (x *BatchInsertDataResponse) GetHeader() *es2.ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *BatchInsertDataResponse) GetItemIds() []int64 {
	if x != nil {
		return x.ItemIds
	}
	return nil
}

type InnerProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *es2.RequestHeader     `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	IndexName     string                 `protobuf:"bytes,2,opt,name=index_name,json=indexName,proto3" json:"index_name,omitempty"`
	QueryVector   []*es2.DataType        `protobuf:"bytes,3,rep,name=query_vector,json=queryVector,proto3" json:"query_vector,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InnerProductRequest) Reset() {
	*x = InnerProductRequest{}
	mi := &file_es2e_es2e_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InnerProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InnerProductRequest) ProtoMessage() {}

func (x *InnerProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_es2e_es2e_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InnerProductRequest.ProtoReflect.Descriptor instead.
func (*InnerProductRequest) Descriptor() ([]byte, []int) {
	return file_es2e_es2e_message_proto_rawDescGZIP(), []int{4}
}

func (x *InnerProductRequest) GetHeader() *es2.RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *InnerProductRequest) GetIndexName() string {
	if x != nil {
		return x.IndexName
	}
	return ""
}

func (x *InnerProductRequest) GetQueryVector() []*es2.DataType {
	if x != nil {
		return x.QueryVector
	}
	return nil
}

type InnerProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *es2.ResponseHeader    `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	CtxtScore     []*es2.CiphertextScore `protobuf:"bytes,2,rep,name=ctxt_score,json=ctxtScore,proto3" json:"ctxt_score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InnerProductResponse) Reset() {
	*x = InnerProductResponse{}
	mi := &file_es2e_es2e_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InnerProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InnerProductResponse) ProtoMessage() {}

func (x *InnerProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_es2e_es2e_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InnerProductResponse.ProtoReflect.Descriptor instead.
func (*InnerProductResponse) Descriptor() ([]byte, []int) {
	return file_es2e_es2e_message_proto_rawDescGZIP(), []int{5}
}

func (x *InnerProductResponse) GetHeader() *es2.ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *InnerProductResponse) GetCtxtScore() []*es2.CiphertextScore {
	if x != nil {
		return x.CtxtScore
	}
	return nil
}

type GetMetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *es2.RequestHeader     `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	IndexName     string                 `protobuf:"bytes,2,opt,name=index_name,json=indexName,proto3" json:"index_name,omitempty"`
	Idx           []*es2.MetadataIdx     `protobuf:"bytes,3,rep,name=idx,proto3" json:"idx,omitempty"`
	OutputFields  []string               `protobuf:"bytes,4,rep,name=output_fields,json=outputFields,proto3" json:"output_fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetadataRequest) Reset() {
	*x = GetMetadataRequest{}
	mi := &file_es2e_es2e_message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetadataRequest) ProtoMessage() {}

func (x *GetMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_es2e_es2e_message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetadataRequest.ProtoReflect.Descriptor instead.
func (*GetMetadataRequest) Descriptor() ([]byte, []int) {
	return file_es2e_es2e_message_proto_rawDescGZIP(), []int{6}
}

func (x *GetMetadataRequest) GetHeader() *es2.RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *GetMetadataRequest) GetIndexName() string {
	if x != nil {
		return x.IndexName
	}
	return ""
}

func (x *GetMetadataRequest) GetIdx() []*es2.MetadataIdx {
	if x != nil {
		return x.Idx
	}
	return nil
}

func (x *GetMetadataRequest) GetOutputFields() []string {
	if x != nil {
		return x.OutputFields
	}
	return nil
}

type GetMetadataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *es2.ResponseHeader    `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Metadata      []*es2.Metadata        `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetadataResponse) Reset() {
	*x = GetMetadataResponse{}
	mi := &file_es2e_es2e_message_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetadataResponse) ProtoMessage() {}

func (x *GetMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_es2e_es2e_message_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetadataResponse.ProtoReflect.Descriptor instead.
func (*GetMetadataResponse) Descriptor() ([]byte, []int) {
	return file_es2e_es2e_message_proto_rawDescGZIP(), []int{7}
}

func (x *GetMetadataResponse) GetHeader() *es2.ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *GetMetadataResponse) GetMetadata() []*es2.Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type GetKeyListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *es2.RequestHeader     `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKeyListRequest) Reset() {
	*x = GetKeyListRequest{}
	mi := &file_es2e_es2e_message_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKeyListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKeyListRequest) ProtoMessage() {}

func (x *GetKeyListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_es2e_es2e_message_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKeyListRequest.ProtoReflect.Descriptor instead.
func (*GetKeyListRequest) Descriptor() ([]byte, []int) {
	return file_es2e_es2e_message_proto_rawDescGZIP(), []int{8}
}

func (x *GetKeyListRequest) GetHeader() *es2.RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

type GetKeyListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *es2.ResponseHeader    `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	KeyId         []string               `protobuf:"bytes,2,rep,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKeyListResponse) Reset() {
	*x = GetKeyListResponse{}
	mi := &file_es2e_es2e_message_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKeyListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKeyListResponse) ProtoMessage() {}

func (x *GetKeyListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_es2e_es2e_message_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKeyListResponse.ProtoReflect.Descriptor instead.
func (*GetKeyListResponse) Descriptor() ([]byte, []int) {
	return file_es2e_es2e_message_proto_rawDescGZIP(), []int{9}
}

func (x *GetKeyListResponse) GetHeader() *es2.ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *GetKeyListResponse) GetKeyId() []string {
	if x != nil {
		return x.KeyId
	}
	return nil
}

type CreateIndexRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *es2.RequestHeader     `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	IndexInfo     *es2.IndexInfo         `protobuf:"bytes,2,opt,name=index_info,json=indexInfo,proto3" json:"index_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateIndexRequest) Reset() {
	*x = CreateIndexRequest{}
	mi := &file_es2e_es2e_message_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateIndexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateIndexRequest) ProtoMessage() {}

func (x *CreateIndexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_es2e_es2e_message_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateIndexRequest.ProtoReflect.Descriptor instead.
func (*CreateIndexRequest) Descriptor() ([]byte, []int) {
	return file_es2e_es2e_message_proto_rawDescGZIP(), []int{10}
}

func (x *CreateIndexRequest) GetHeader() *es2.RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *CreateIndexRequest) GetIndexInfo() *es2.IndexInfo {
	if x != nil {
		return x.IndexInfo
	}
	return nil
}

type CreateIndexResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *es2.ResponseHeader    `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateIndexResponse) Reset() {
	*x = CreateIndexResponse{}
	mi := &file_es2e_es2e_message_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateIndexResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateIndexResponse) ProtoMessage() {}

func (x *CreateIndexResponse) ProtoReflect() protoreflect.Message {
	mi := &file_es2e_es2e_message_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateIndexResponse.ProtoReflect.Descriptor instead.
func (*CreateIndexResponse) Descriptor() ([]byte, []int) {
	return file_es2e_es2e_message_proto_rawDescGZIP(), []int{11}
}

func (x *CreateIndexResponse) GetHeader() *es2.ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

type DeleteIndexRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *es2.RequestHeader     `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	IndexName     string                 `protobuf:"bytes,2,opt,name=index_name,json=indexName,proto3" json:"index_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteIndexRequest) Reset() {
	*x = DeleteIndexRequest{}
	mi := &file_es2e_es2e_message_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteIndexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteIndexRequest) ProtoMessage() {}

func (x *DeleteIndexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_es2e_es2e_message_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteIndexRequest.ProtoReflect.Descriptor instead.
func (*DeleteIndexRequest) Descriptor() ([]byte, []int) {
	return file_es2e_es2e_message_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteIndexRequest) GetHeader() *es2.RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *DeleteIndexRequest) GetIndexName() string {
	if x != nil {
		return x.IndexName
	}
	return ""
}

type DeleteIndexResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *es2.ResponseHeader    `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteIndexResponse) Reset() {
	*x = DeleteIndexResponse{}
	mi := &file_es2e_es2e_message_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteIndexResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteIndexResponse) ProtoMessage() {}

func (x *DeleteIndexResponse) ProtoReflect() protoreflect.Message {
	mi := &file_es2e_es2e_message_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteIndexResponse.ProtoReflect.Descriptor instead.
func (*DeleteIndexResponse) Descriptor() ([]byte, []int) {
	return file_es2e_es2e_message_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteIndexResponse) GetHeader() *es2.ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

type RegisterKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *es2.RequestHeader     `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	KeyInfo       *es2.KeyInfo           `protobuf:"bytes,2,opt,name=key_info,json=keyInfo,proto3" json:"key_info,omitempty"`
	Key           *es2.Key               `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterKeyRequest) Reset() {
	*x = RegisterKeyRequest{}
	mi := &file_es2e_es2e_message_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterKeyRequest) ProtoMessage() {}

func (x *RegisterKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_es2e_es2e_message_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterKeyRequest.ProtoReflect.Descriptor instead.
func (*RegisterKeyRequest) Descriptor() ([]byte, []int) {
	return file_es2e_es2e_message_proto_rawDescGZIP(), []int{14}
}

func (x *RegisterKeyRequest) GetHeader() *es2.RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *RegisterKeyRequest) GetKeyInfo() *es2.KeyInfo {
	if x != nil {
		return x.KeyInfo
	}
	return nil
}

func (x *RegisterKeyRequest) GetKey() *es2.Key {
	if x != nil {
		return x.Key
	}
	return nil
}

type RegisterKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *es2.ResponseHeader    `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterKeyResponse) Reset() {
	*x = RegisterKeyResponse{}
	mi := &file_es2e_es2e_message_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterKeyResponse) ProtoMessage() {}

func (x *RegisterKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_es2e_es2e_message_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterKeyResponse.ProtoReflect.Descriptor instead.
func (*RegisterKeyResponse) Descriptor() ([]byte, []int) {
	return file_es2e_es2e_message_proto_rawDescGZIP(), []int{15}
}

func (x *RegisterKeyResponse) GetHeader() *es2.ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

type LoadKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *es2.RequestHeader     `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	KeyId         string                 `protobuf:"bytes,2,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadKeyRequest) Reset() {
	*x = LoadKeyRequest{}
	mi := &file_es2e_es2e_message_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadKeyRequest) ProtoMessage() {}

func (x *LoadKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_es2e_es2e_message_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadKeyRequest.ProtoReflect.Descriptor instead.
func (*LoadKeyRequest) Descriptor() ([]byte, []int) {
	return file_es2e_es2e_message_proto_rawDescGZIP(), []int{16}
}

func (x *LoadKeyRequest) GetHeader() *es2.RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *LoadKeyRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

type LoadKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *es2.ResponseHeader    `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadKeyResponse) Reset() {
	*x = LoadKeyResponse{}
	mi := &file_es2e_es2e_message_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadKeyResponse) ProtoMessage() {}

func (x *LoadKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_es2e_es2e_message_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadKeyResponse.ProtoReflect.Descriptor instead.
func (*LoadKeyResponse) Descriptor() ([]byte, []int) {
	return file_es2e_es2e_message_proto_rawDescGZIP(), []int{17}
}

func (x *LoadKeyResponse) GetHeader() *es2.ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

type UnloadKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *es2.RequestHeader     `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	KeyId         string                 `protobuf:"bytes,2,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnloadKeyRequest) Reset() {
	*x = UnloadKeyRequest{}
	mi := &file_es2e_es2e_message_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnloadKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnloadKeyRequest) ProtoMessage() {}

func (x *UnloadKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_es2e_es2e_message_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnloadKeyRequest.ProtoReflect.Descriptor instead.
func (*UnloadKeyRequest) Descriptor() ([]byte, []int) {
	return file_es2e_es2e_message_proto_rawDescGZIP(), []int{18}
}

func (x *UnloadKeyRequest) GetHeader() *es2.RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *UnloadKeyRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

type UnloadKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *es2.ResponseHeader    `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnloadKeyResponse) Reset() {
	*x = UnloadKeyResponse{}
	mi := &file_es2e_es2e_message_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnloadKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnloadKeyResponse) ProtoMessage() {}

func (x *UnloadKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_es2e_es2e_message_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnloadKeyResponse.ProtoReflect.Descriptor instead.
func (*UnloadKeyResponse) Descriptor() ([]byte, []int) {
	return file_es2e_es2e_message_proto_rawDescGZIP(), []int{19}
}

func (x *UnloadKeyResponse) GetHeader() *es2.ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

type DeleteKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *es2.RequestHeader     `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	KeyId         string                 `protobuf:"bytes,2,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteKeyRequest) Reset() {
	*x = DeleteKeyRequest{}
	mi := &file_es2e_es2e_message_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKeyRequest) ProtoMessage() {}

func (x *DeleteKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_es2e_es2e_message_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKeyRequest.ProtoReflect.Descriptor instead.
func (*DeleteKeyRequest) Descriptor() ([]byte, []int) {
	return file_es2e_es2e_message_proto_rawDescGZIP(), []int{20}
}

func (x *DeleteKeyRequest) GetHeader() *es2.RequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *DeleteKeyRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

type DeleteKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *es2.ResponseHeader    `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteKeyResponse) Reset() {
	*x = DeleteKeyResponse{}
	mi := &file_es2e_es2e_message_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKeyResponse) ProtoMessage() {}

func (x *DeleteKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_es2e_es2e_message_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKeyResponse.ProtoReflect.Descriptor instead.
func (*DeleteKeyResponse) Descriptor() ([]byte, []int) {
	return file_es2e_es2e_message_proto_rawDescGZIP(), []int{21}
}

func (x *DeleteKeyResponse) GetHeader() *es2.ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

var File_es2e_es2e_message_proto protoreflect.FileDescriptor

const file_es2e_es2e_message_proto_rawDesc = "" +
	"\n" +
	"\x17es2e/es2e-message.proto\x12\x04ES2E\x1a\x0ees2/type.proto\x1a\x18es2/common-message.proto\"b\n" +
	"\x13GetIndexListRequest\x12*\n" +
	"\x06header\x18\x01 \x01(\v2\x12.ES2.RequestHeaderR\x06header\x12\x1f\n" +
	"\vloaded_only\x18\x02 \x01(\bR\n" +
	"loadedOnly\"d\n" +
	"\x14GetIndexListResponse\x12+\n" +
	"\x06header\x18\x01 \x01(\v2\x13.ES2.ResponseHeaderR\x06header\x12\x1f\n" +
	"\vindex_names\x18\x02 \x03(\tR\n" +
	"indexNames\"\x9e\x01\n" +
	"\x16BatchInsertDataRequest\x12*\n" +
	"\x06header\x18\x01 \x01(\v2\x12.ES2.RequestHeaderR\x06header\x12\x1d\n" +
	"\n" +
	"index_name\x18\x02 \x01(\tR\tindexName\x129\n" +
	"\x0epacked_vectors\x18\x03 \x03(\v2\x12.ES2.PackedVectorsR\rpackedVectors\"a\n" +
	"\x17BatchInsertDataResponse\x12+\n" +
	"\x06header\x18\x01 \x01(\v2\x13.ES2.ResponseHeaderR\x06header\x12\x19\n" +
	"\bitem_ids\x18\x02 \x03(\x03R\aitemIds\"\x92\x01\n" +
	"\x13InnerProductRequest\x12*\n" +
	"\x06header\x18\x01 \x01(\v2\x12.ES2.RequestHeaderR\x06header\x12\x1d\n" +
	"\n" +
	"index_name\x18\x02 \x01(\tR\tindexName\x120\n" +
	"\fquery_vector\x18\x03 \x03(\v2\r.ES2.DataTypeR\vqueryVector\"x\n" +
	"\x14InnerProductResponse\x12+\n" +
	"\x06header\x18\x01 \x01(\v2\x13.ES2.ResponseHeaderR\x06header\x123\n" +
	"\n" +
	"ctxt_score\x18\x02 \x03(\v2\x14.ES2.CiphertextScoreR\tctxtScore\"\xa8\x01\n" +
	"\x12GetMetadataRequest\x12*\n" +
	"\x06header\x18\x01 \x01(\v2\x12.ES2.RequestHeaderR\x06header\x12\x1d\n" +
	"\n" +
	"index_name\x18\x02 \x01(\tR\tindexName\x12\"\n" +
	"\x03idx\x18\x03 \x03(\v2\x10.ES2.MetadataIdxR\x03idx\x12#\n" +
	"\routput_fields\x18\x04 \x03(\tR\foutputFields\"m\n" +
	"\x13GetMetadataResponse\x12+\n" +
	"\x06header\x18\x01 \x01(\v2\x13.ES2.ResponseHeaderR\x06header\x12)\n" +
	"\bmetadata\x18\x02 \x03(\v2\r.ES2.MetadataR\bmetadata\"?\n" +
	"\x11GetKeyListRequest\x12*\n" +
	"\x06header\x18\x01 \x01(\v2\x12.ES2.RequestHeaderR\x06header\"X\n" +
	"\x12GetKeyListResponse\x12+\n" +
	"\x06header\x18\x01 \x01(\v2\x13.ES2.ResponseHeaderR\x06header\x12\x15\n" +
	"\x06key_id\x18\x02 \x03(\tR\x05keyId\"o\n" +
	"\x12CreateIndexRequest\x12*\n" +
	"\x06header\x18\x01 \x01(\v2\x12.ES2.RequestHeaderR\x06header\x12-\n" +
	"\n" +
	"index_info\x18\x02 \x01(\v2\x0e.ES2.IndexInfoR\tindexInfo\"B\n" +
	"\x13CreateIndexResponse\x12+\n" +
	"\x06header\x18\x01 \x01(\v2\x13.ES2.ResponseHeaderR\x06header\"_\n" +
	"\x12DeleteIndexRequest\x12*\n" +
	"\x06header\x18\x01 \x01(\v2\x12.ES2.RequestHeaderR\x06header\x12\x1d\n" +
	"\n" +
	"index_name\x18\x02 \x01(\tR\tindexName\"B\n" +
	"\x13DeleteIndexResponse\x12+\n" +
	"\x06header\x18\x01 \x01(\v2\x13.ES2.ResponseHeaderR\x06header\"\x85\x01\n" +
	"\x12RegisterKeyRequest\x12*\n" +
	"\x06header\x18\x01 \x01(\v2\x12.ES2.RequestHeaderR\x06header\x12'\n" +
	"\bkey_info\x18\x02 \x01(\v2\f.ES2.KeyInfoR\akeyInfo\x12\x1a\n" +
	"\x03key\x18\x03 \x01(\v2\b.ES2.KeyR\x03key\"B\n" +
	"\x13RegisterKeyResponse\x12+\n" +
	"\x06header\x18\x01 \x01(\v2\x13.ES2.ResponseHeaderR\x06header\"S\n" +
	"\x0eLoadKeyRequest\x12*\n" +
	"\x06header\x18\x01 \x01(\v2\x12.ES2.RequestHeaderR\x06header\x12\x15\n" +
	"\x06key_id\x18\x02 \x01(\tR\x05keyId\">\n" +
	"\x0fLoadKeyResponse\x12+\n" +
	"\x06header\x18\x01 \x01(\v2\x13.ES2.ResponseHeaderR\x06header\"U\n" +
	"\x10UnloadKeyRequest\x12*\n" +
	"\x06header\x18\x01 \x01(\v2\x12.ES2.RequestHeaderR\x06header\x12\x15\n" +
	"\x06key_id\x18\x02 \x01(\tR\x05keyId\"@\n" +
	"\x11UnloadKeyResponse\x12+\n" +
	"\x06header\x18\x01 \x01(\v2\x13.ES2.ResponseHeaderR\x06header\"U\n" +
	"\x10DeleteKeyRequest\x12*\n" +
	"\x06header\x18\x01 \x01(\v2\x12.ES2.RequestHeaderR\x06header\x12\x15\n" +
	"\x06key_id\x18\x02 \x01(\tR\x05keyId\"@\n" +
	"\x11DeleteKeyResponse\x12+\n" +
	"\x06header\x18\x01 \x01(\v2\x13.ES2.ResponseHeaderR\x06headerBIZGgithub.com/CryptoLabInc/envector-go-sdk/internal/transport/pb/es2e;es2eb\x06proto3"

var (
	file_es2e_es2e_message_proto_rawDescOnce sync.Once
	file_es2e_es2e_message_proto_rawDescData []byte
)

func file_es2e_es2e_message_proto_rawDescGZIP() []byte {
	file_es2e_es2e_message_proto_rawDescOnce.Do(func() {
		file_es2e_es2e_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_es2e_es2e_message_proto_rawDesc), len(file_es2e_es2e_message_proto_rawDesc)))
	})
	return file_es2e_es2e_message_proto_rawDescData
}

var file_es2e_es2e_message_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_es2e_es2e_message_proto_goTypes = []any{
	(*GetIndexListRequest)(nil),     // 0: ES2E.GetIndexListRequest
	(*GetIndexListResponse)(nil),    // 1: ES2E.GetIndexListResponse
	(*BatchInsertDataRequest)(nil),  // 2: ES2E.BatchInsertDataRequest
	(*BatchInsertDataResponse)(nil), // 3: ES2E.BatchInsertDataResponse
	(*InnerProductRequest)(nil),     // 4: ES2E.InnerProductRequest
	(*InnerProductResponse)(nil),    // 5: ES2E.InnerProductResponse
	(*GetMetadataRequest)(nil),      // 6: ES2E.GetMetadataRequest
	(*GetMetadataResponse)(nil),     // 7: ES2E.GetMetadataResponse
	(*GetKeyListRequest)(nil),       // 8: ES2E.GetKeyListRequest
	(*GetKeyListResponse)(nil),      // 9: ES2E.GetKeyListResponse
	(*CreateIndexRequest)(nil),      // 10: ES2E.CreateIndexRequest
	(*CreateIndexResponse)(nil),     // 11: ES2E.CreateIndexResponse
	(*DeleteIndexRequest)(nil),      // 12: ES2E.DeleteIndexRequest
	(*DeleteIndexResponse)(nil),     // 13: ES2E.DeleteIndexResponse
	(*RegisterKeyRequest)(nil),      // 14: ES2E.RegisterKeyRequest
	(*RegisterKeyResponse)(nil),     // 15: ES2E.RegisterKeyResponse
	(*LoadKeyRequest)(nil),          // 16: ES2E.LoadKeyRequest
	(*LoadKeyResponse)(nil),         // 17: ES2E.LoadKeyResponse
	(*UnloadKeyRequest)(nil),        // 18: ES2E.UnloadKeyRequest
	(*UnloadKeyResponse)(nil),       // 19: ES2E.UnloadKeyResponse
	(*DeleteKeyRequest)(nil),        // 20: ES2E.DeleteKeyRequest
	(*DeleteKeyResponse)(nil),       // 21: ES2E.DeleteKeyResponse
	(*es2.RequestHeader)(nil),       // 22: ES2.RequestHeader
	(*es2.ResponseHeader)(nil),      // 23: ES2.ResponseHeader
	(*es2.PackedVectors)(nil),       // 24: ES2.PackedVectors
	(*es2.DataType)(nil),            // 25: ES2.DataType
	(*es2.CiphertextScore)(nil),     // 26: ES2.CiphertextScore
	(*es2.MetadataIdx)(nil),         // 27: ES2.MetadataIdx
	(*es2.Metadata)(nil),            // 28: ES2.Metadata
	(*es2.IndexInfo)(nil),           // 29: ES2.IndexInfo
	(*es2.KeyInfo)(nil),             // 30: ES2.KeyInfo
	(*es2.Key)(nil),                 // 31: ES2.Key
}
var file_es2e_es2e_message_proto_depIdxs = []int32{
	22, // 0: ES2E.GetIndexListRequest.header:type_name -> ES2.RequestHeader
	23, // 1: ES2E.GetIndexListResponse.header:type_name -> ES2.ResponseHeader
	22, // 2: ES2E.BatchInsertDataRequest.header:type_name -> ES2.RequestHeader
	24, // 3: ES2E.BatchInsertDataRequest.packed_vectors:type_name -> ES2.PackedVectors
	23, // 4: ES2E.BatchInsertDataResponse.header:type_name -> ES2.ResponseHeader
	22, // 5: ES2E.InnerProductRequest.header:type_name -> ES2.RequestHeader
	25, // 6: ES2E.InnerProductRequest.query_vector:type_name -> ES2.DataType
	23, // 7: ES2E.InnerProductResponse.header:type_name -> ES2.ResponseHeader
	26, // 8: ES2E.InnerProductResponse.ctxt_score:type_name -> ES2.CiphertextScore
	22, // 9: ES2E.GetMetadataRequest.header:type_name -> ES2.RequestHeader
	27, // 10: ES2E.GetMetadataRequest.idx:type_name -> ES2.MetadataIdx
	23, // 11: ES2E.GetMetadataResponse.header:type_name -> ES2.ResponseHeader
	28, // 12: ES2E.GetMetadataResponse.metadata:type_name -> ES2.Metadata
	22, // 13: ES2E.GetKeyListRequest.header:type_name -> ES2.RequestHeader
	23, // 14: ES2E.GetKeyListResponse.header:type_name -> ES2.ResponseHeader
	22, // 15: ES2E.CreateIndexRequest.header:type_name -> ES2.RequestHeader
	29, // 16: ES2E.CreateIndexRequest.index_info:type_name -> ES2.IndexInfo
	23, // 17: ES2E.CreateIndexResponse.header:type_name -> ES2.ResponseHeader
	22, // 18: ES2E.DeleteIndexRequest.header:type_name -> ES2.RequestHeader
	23, // 19: ES2E.DeleteIndexResponse.header:type_name -> ES2.ResponseHeader
	22, // 20: ES2E.RegisterKeyRequest.header:type_name -> ES2.RequestHeader
	30, // 21: ES2E.RegisterKeyRequest.key_info:type_name -> ES2.KeyInfo
	31, // 22: ES2E.RegisterKeyRequest.key:type_name -> ES2.Key
	23, // 23: ES2E.RegisterKeyResponse.header:type_name -> ES2.ResponseHeader
	22, // 24: ES2E.LoadKeyRequest.header:type_name -> ES2.RequestHeader
	23, // 25: ES2E.LoadKeyResponse.header:type_name -> ES2.ResponseHeader
	22, // 26: ES2E.UnloadKeyRequest.header:type_name -> ES2.RequestHeader
	23, // 27: ES2E.UnloadKeyResponse.header:type_name -> ES2.ResponseHeader
	22, // 28: ES2E.DeleteKeyRequest.header:type_name -> ES2.RequestHeader
	23, // 29: ES2E.DeleteKeyResponse.header:type_name -> ES2.ResponseHeader
	30, // [30:30] is the sub-list for method output_type
	30, // [30:30] is the sub-list for method input_type
	30, // [30:30] is the sub-list for extension type_name
	30, // [30:30] is the sub-list for extension extendee
	0,  // [0:30] is the sub-list for field type_name
}

func init() { file_es2e_es2e_message_proto_init() }
func file_es2e_es2e_message_proto_init() {
	if File_es2e_es2e_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_es2e_es2e_message_proto_rawDesc), len(file_es2e_es2e_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_es2e_es2e_message_proto_goTypes,
		DependencyIndexes: file_es2e_es2e_message_proto_depIdxs,
		MessageInfos:      file_es2e_es2e_message_proto_msgTypes,
	}.Build()
	File_es2e_es2e_message_proto = out.File
	file_es2e_es2e_message_proto_goTypes = nil
	file_es2e_es2e_message_proto_depIdxs = nil
}
