// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: es2e/es2e-api.proto

package es2e

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_es2e_es2e_api_proto protoreflect.FileDescriptor

const file_es2e_es2e_api_proto_rawDesc = "" +
	"\n" +
	"\x13es2e/es2e-api.proto\x12\x04ES2E\x1a\x17es2e/es2e-message.proto2\x86\x06\n" +
	"\vES2EService\x12G\n" +
	"\x0eget_index_list\x12\x19.ES2E.GetIndexListRequest\x1a\x1a.ES2E.GetIndexListResponse\x12C\n" +
	"\fget_metadata\x12\x18.ES2E.GetMetadataRequest\x1a\x19.ES2E.GetMetadataResponse\x12H\n" +
	"\rinner_product\x12\x19.ES2E.InnerProductRequest\x1a\x1a.ES2E.InnerProductResponse0\x01\x12R\n" +
	"\x11batch_insert_data\x12\x1c.ES2E.BatchInsertDataRequest\x1a\x1d.ES2E.BatchInsertDataResponse(\x01\x12E\n" +
	"\fcreate_index\x12\x18.ES2E.CreateIndexRequest\x1a\x19.ES2E.CreateIndexResponse(\x01\x12A\n" +
	"\fget_key_list\x12\x17.ES2E.GetKeyListRequest\x1a\x18.ES2E.GetKeyListResponse\x12E\n" +
	"\fregister_key\x12\x18.ES2E.RegisterKeyRequest\x1a\x19.ES2E.RegisterKeyResponse(\x01\x127\n" +
	"\bload_key\x12\x14.ES2E.LoadKeyRequest\x1a\x15.ES2E.LoadKeyResponse\x12=\n" +
	"\n" +
	"unload_key\x12\x16.ES2E.UnloadKeyRequest\x1a\x17.ES2E.UnloadKeyResponse\x12=\n" +
	"\n" +
	"delete_key\x12\x16.ES2E.DeleteKeyRequest\x1a\x17.ES2E.DeleteKeyResponse\x12C\n" +
	"\fdelete_index\x12\x18.ES2E.DeleteIndexRequest\x1a\x19.ES2E.DeleteIndexResponseBIZGgithub.com/CryptoLabInc/envector-go-sdk/internal/transport/pb/es2e;es2eb\x06proto3"

var file_es2e_es2e_api_proto_goTypes = []any{
	(*GetIndexListRequest)(nil),     // 0: ES2E.GetIndexListRequest
	(*GetMetadataRequest)(nil),      // 1: ES2E.GetMetadataRequest
	(*InnerProductRequest)(nil),     // 2: ES2E.InnerProductRequest
	(*BatchInsertDataRequest)(nil),  // 3: ES2E.BatchInsertDataRequest
	(*CreateIndexRequest)(nil),      // 4: ES2E.CreateIndexRequest
	(*GetKeyListRequest)(nil),       // 5: ES2E.GetKeyListRequest
	(*RegisterKeyRequest)(nil),      // 6: ES2E.RegisterKeyRequest
	(*LoadKeyRequest)(nil),          // 7: ES2E.LoadKeyRequest
	(*UnloadKeyRequest)(nil),        // 8: ES2E.UnloadKeyRequest
	(*DeleteKeyRequest)(nil),        // 9: ES2E.DeleteKeyRequest
	(*DeleteIndexRequest)(nil),      // 10: ES2E.DeleteIndexRequest
	(*GetIndexListResponse)(nil),    // 11: ES2E.GetIndexListResponse
	(*GetMetadataResponse)(nil),     // 12: ES2E.GetMetadataResponse
	(*InnerProductResponse)(nil),    // 13: ES2E.InnerProductResponse
	(*BatchInsertDataResponse)(nil), // 14: ES2E.BatchInsertDataResponse
	(*CreateIndexResponse)(nil),     // 15: ES2E.CreateIndexResponse
	(*GetKeyListResponse)(nil),      // 16: ES2E.GetKeyListResponse
	(*RegisterKeyResponse)(nil),     // 17: ES2E.RegisterKeyResponse
	(*LoadKeyResponse)(nil),         // 18: ES2E.LoadKeyResponse
	(*UnloadKeyResponse)(nil),       // 19: ES2E.UnloadKeyResponse
	(*DeleteKeyResponse)(nil),       // 20: ES2E.DeleteKeyResponse
	(*DeleteIndexResponse)(nil),     // 21: ES2E.DeleteIndexResponse
}
var file_es2e_es2e_api_proto_depIdxs = []int32{
	0,  // 0: ES2E.ES2EService.get_index_list:input_type -> ES2E.GetIndexListRequest
	1,  // 1: ES2E.ES2EService.get_metadata:input_type -> ES2E.GetMetadataRequest
	2,  // 2: ES2E.ES2EService.inner_product:input_type -> ES2E.InnerProductRequest
	3,  // 3: ES2E.ES2EService.batch_insert_data:input_type -> ES2E.BatchInsertDataRequest
	4,  // 4: ES2E.ES2EService.create_index:input_type -> ES2E.CreateIndexRequest
	5,  // 5: ES2E.ES2EService.get_key_list:input_type -> ES2E.GetKeyListRequest
	6,  // 6: ES2E.ES2EService.register_key:input_type -> ES2E.RegisterKeyRequest
	7,  // 7: ES2E.ES2EService.load_key:input_type -> ES2E.LoadKeyRequest
	8,  // 8: ES2E.ES2EService.unload_key:input_type -> ES2E.UnloadKeyRequest
	9,  // 9: ES2E.ES2EService.delete_key:input_type -> ES2E.DeleteKeyRequest
	10, // 10: ES2E.ES2EService.delete_index:input_type -> ES2E.DeleteIndexRequest
	11, // 11: ES2E.ES2EService.get_index_list:output_type -> ES2E.GetIndexListResponse
	12, // 12: ES2E.ES2EService.get_metadata:output_type -> ES2E.GetMetadataResponse
	13, // 13: ES2E.ES2EService.inner_product:output_type -> ES2E.InnerProductResponse
	14, // 14: ES2E.ES2EService.batch_insert_data:output_type -> ES2E.BatchInsertDataResponse
	15, // 15: ES2E.ES2EService.create_index:output_type -> ES2E.CreateIndexResponse
	16, // 16: ES2E.ES2EService.get_key_list:output_type -> ES2E.GetKeyListResponse
	17, // 17: ES2E.ES2EService.register_key:output_type -> ES2E.RegisterKeyResponse
	18, // 18: ES2E.ES2EService.load_key:output_type -> ES2E.LoadKeyResponse
	19, // 19: ES2E.ES2EService.unload_key:output_type -> ES2E.UnloadKeyResponse
	20, // 20: ES2E.ES2EService.delete_key:output_type -> ES2E.DeleteKeyResponse
	21, // 21: ES2E.ES2EService.delete_index:output_type -> ES2E.DeleteIndexResponse
	11, // [11:22] is the sub-list for method output_type
	0,  // [0:11] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_es2e_es2e_api_proto_init() }
func file_es2e_es2e_api_proto_init() {
	if File_es2e_es2e_api_proto != nil {
		return
	}
	file_es2e_es2e_message_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_es2e_es2e_api_proto_rawDesc), len(file_es2e_es2e_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_es2e_es2e_api_proto_goTypes,
		DependencyIndexes: file_es2e_es2e_api_proto_depIdxs,
	}.Build()
	File_es2e_es2e_api_proto = out.File
	file_es2e_es2e_api_proto_goTypes = nil
	file_es2e_es2e_api_proto_depIdxs = nil
}
