// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: es2e/es2e-api.proto

package es2e

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ES2EService_GetIndexList_FullMethodName    = "/ES2E.ES2EService/get_index_list"
	ES2EService_GetMetadata_FullMethodName     = "/ES2E.ES2EService/get_metadata"
	ES2EService_InnerProduct_FullMethodName    = "/ES2E.ES2EService/inner_product"
	ES2EService_BatchInsertData_FullMethodName = "/ES2E.ES2EService/batch_insert_data"
	ES2EService_CreateIndex_FullMethodName     = "/ES2E.ES2EService/create_index"
	ES2EService_GetKeyList_FullMethodName      = "/ES2E.ES2EService/get_key_list"
	ES2EService_RegisterKey_FullMethodName     = "/ES2E.ES2EService/register_key"
	ES2EService_LoadKey_FullMethodName         = "/ES2E.ES2EService/load_key"
	ES2EService_UnloadKey_FullMethodName       = "/ES2E.ES2EService/unload_key"
	ES2EService_DeleteKey_FullMethodName       = "/ES2E.ES2EService/delete_key"
	ES2EService_DeleteIndex_FullMethodName     = "/ES2E.ES2EService/delete_index"
)

// ES2EServiceClient is the client API for ES2EService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ES2EServiceClient interface {
	GetIndexList(ctx context.Context, in *GetIndexListRequest, opts ...grpc.CallOption) (*GetIndexListResponse, error)
	GetMetadata(ctx context.Context, in *GetMetadataRequest, opts ...grpc.CallOption) (*GetMetadataResponse, error)
	InnerProduct(ctx context.Context, in *InnerProductRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[InnerProductResponse], error)
	BatchInsertData(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[BatchInsertDataRequest, BatchInsertDataResponse], error)
	CreateIndex(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[CreateIndexRequest, CreateIndexResponse], error)
	GetKeyList(ctx context.Context, in *GetKeyListRequest, opts ...grpc.CallOption) (*GetKeyListResponse, error)
	RegisterKey(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[RegisterKeyRequest, RegisterKeyResponse], error)
	LoadKey(ctx context.Context, in *LoadKeyRequest, opts ...grpc.CallOption) (*LoadKeyResponse, error)
	UnloadKey(ctx context.Context, in *UnloadKeyRequest, opts ...grpc.CallOption) (*UnloadKeyResponse, error)
	DeleteKey(ctx context.Context, in *DeleteKeyRequest, opts ...grpc.CallOption) (*DeleteKeyResponse, error)
	DeleteIndex(ctx context.Context, in *DeleteIndexRequest, opts ...grpc.CallOption) (*DeleteIndexResponse, error)
}

type eS2EServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewES2EServiceClient(cc grpc.ClientConnInterface) ES2EServiceClient {
	return &eS2EServiceClient{cc}
}

func (c *eS2EServiceClient) GetIndexList(ctx context.Context, in *GetIndexListRequest, opts ...grpc.CallOption) (*GetIndexListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetIndexListResponse)
	err := c.cc.Invoke(ctx, ES2EService_GetIndexList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eS2EServiceClient) GetMetadata(ctx context.Context, in *GetMetadataRequest, opts ...grpc.CallOption) (*GetMetadataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMetadataResponse)
	err := c.cc.Invoke(ctx, ES2EService_GetMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eS2EServiceClient) InnerProduct(ctx context.Context, in *InnerProductRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[InnerProductResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ES2EService_ServiceDesc.Streams[0], ES2EService_InnerProduct_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[InnerProductRequest, InnerProductResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ES2EService_InnerProductClient = grpc.ServerStreamingClient[InnerProductResponse]

func (c *eS2EServiceClient) BatchInsertData(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[BatchInsertDataRequest, BatchInsertDataResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ES2EService_ServiceDesc.Streams[1], ES2EService_BatchInsertData_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[BatchInsertDataRequest, BatchInsertDataResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ES2EService_BatchInsertDataClient = grpc.ClientStreamingClient[BatchInsertDataRequest, BatchInsertDataResponse]

func (c *eS2EServiceClient) CreateIndex(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[CreateIndexRequest, CreateIndexResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ES2EService_ServiceDesc.Streams[2], ES2EService_CreateIndex_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CreateIndexRequest, CreateIndexResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ES2EService_CreateIndexClient = grpc.ClientStreamingClient[CreateIndexRequest, CreateIndexResponse]

func (c *eS2EServiceClient) GetKeyList(ctx context.Context, in *GetKeyListRequest, opts ...grpc.CallOption) (*GetKeyListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetKeyListResponse)
	err := c.cc.Invoke(ctx, ES2EService_GetKeyList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eS2EServiceClient) RegisterKey(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[RegisterKeyRequest, RegisterKeyResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ES2EService_ServiceDesc.Streams[3], ES2EService_RegisterKey_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RegisterKeyRequest, RegisterKeyResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ES2EService_RegisterKeyClient = grpc.ClientStreamingClient[RegisterKeyRequest, RegisterKeyResponse]

func (c *eS2EServiceClient) LoadKey(ctx context.Context, in *LoadKeyRequest, opts ...grpc.CallOption) (*LoadKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoadKeyResponse)
	err := c.cc.Invoke(ctx, ES2EService_LoadKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eS2EServiceClient) UnloadKey(ctx context.Context, in *UnloadKeyRequest, opts ...grpc.CallOption) (*UnloadKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnloadKeyResponse)
	err := c.cc.Invoke(ctx, ES2EService_UnloadKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eS2EServiceClient) DeleteKey(ctx context.Context, in *DeleteKeyRequest, opts ...grpc.CallOption) (*DeleteKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteKeyResponse)
	err := c.cc.Invoke(ctx, ES2EService_DeleteKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eS2EServiceClient) DeleteIndex(ctx context.Context, in *DeleteIndexRequest, opts ...grpc.CallOption) (*DeleteIndexResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteIndexResponse)
	err := c.cc.Invoke(ctx, ES2EService_DeleteIndex_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ES2EServiceServer is the server API for ES2EService service.
// All implementations should embed UnimplementedES2EServiceServer
// for forward compatibility.
type ES2EServiceServer interface {
	GetIndexList(context.Context, *GetIndexListRequest) (*GetIndexListResponse, error)
	GetMetadata(context.Context, *GetMetadataRequest) (*GetMetadataResponse, error)
	InnerProduct(*InnerProductRequest, grpc.ServerStreamingServer[InnerProductResponse]) error
	BatchInsertData(grpc.ClientStreamingServer[BatchInsertDataRequest, BatchInsertDataResponse]) error
	CreateIndex(grpc.ClientStreamingServer[CreateIndexRequest, CreateIndexResponse]) error
	GetKeyList(context.Context, *GetKeyListRequest) (*GetKeyListResponse, error)
	RegisterKey(grpc.ClientStreamingServer[RegisterKeyRequest, RegisterKeyResponse]) error
	LoadKey(context.Context, *LoadKeyRequest) (*LoadKeyResponse, error)
	UnloadKey(context.Context, *UnloadKeyRequest) (*UnloadKeyResponse, error)
	DeleteKey(context.Context, *DeleteKeyRequest) (*DeleteKeyResponse, error)
	DeleteIndex(context.Context, *DeleteIndexRequest) (*DeleteIndexResponse, error)
}

// UnimplementedES2EServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedES2EServiceServer struct{}

func (UnimplementedES2EServiceServer) GetIndexList(context.Context, *GetIndexListRequest) (*GetIndexListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIndexList not implemented")
}
func (UnimplementedES2EServiceServer) GetMetadata(context.Context, *GetMetadataRequest) (*GetMetadataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMetadata not implemented")
}
func (UnimplementedES2EServiceServer) InnerProduct(*InnerProductRequest, grpc.ServerStreamingServer[InnerProductResponse]) error {
	return status.Errorf(codes.Unimplemented, "method InnerProduct not implemented")
}
func (UnimplementedES2EServiceServer) BatchInsertData(grpc.ClientStreamingServer[BatchInsertDataRequest, BatchInsertDataResponse]) error {
	return status.Errorf(codes.Unimplemented, "method BatchInsertData not implemented")
}
func (UnimplementedES2EServiceServer) CreateIndex(grpc.ClientStreamingServer[CreateIndexRequest, CreateIndexResponse]) error {
	return status.Errorf(codes.Unimplemented, "method CreateIndex not implemented")
}
func (UnimplementedES2EServiceServer) GetKeyList(context.Context, *GetKeyListRequest) (*GetKeyListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetKeyList not implemented")
}
func (UnimplementedES2EServiceServer) RegisterKey(grpc.ClientStreamingServer[RegisterKeyRequest, RegisterKeyResponse]) error {
	return status.Errorf(codes.Unimplemented, "method RegisterKey not implemented")
}
func (UnimplementedES2EServiceServer) LoadKey(context.Context, *LoadKeyRequest) (*LoadKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoadKey not implemented")
}
func (UnimplementedES2EServiceServer) UnloadKey(context.Context, *UnloadKeyRequest) (*UnloadKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnloadKey not implemented")
}
func (UnimplementedES2EServiceServer) DeleteKey(context.Context, *DeleteKeyRequest) (*DeleteKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteKey not implemented")
}
func (UnimplementedES2EServiceServer) DeleteIndex(context.Context, *DeleteIndexRequest) (*DeleteIndexResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteIndex not implemented")
}
func (UnimplementedES2EServiceServer) testEmbeddedByValue() {}

// UnsafeES2EServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ES2EServiceServer will
// result in compilation errors.
type UnsafeES2EServiceServer interface {
	mustEmbedUnimplementedES2EServiceServer()
}

func RegisterES2EServiceServer(s grpc.ServiceRegistrar, srv ES2EServiceServer) {
	// If the following call pancis, it indicates UnimplementedES2EServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ES2EService_ServiceDesc, srv)
}

func _ES2EService_GetIndexList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIndexListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ES2EServiceServer).GetIndexList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ES2EService_GetIndexList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ES2EServiceServer).GetIndexList(ctx, req.(*GetIndexListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ES2EService_GetMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ES2EServiceServer).GetMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ES2EService_GetMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ES2EServiceServer).GetMetadata(ctx, req.(*GetMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ES2EService_InnerProduct_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(InnerProductRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ES2EServiceServer).InnerProduct(m, &grpc.GenericServerStream[InnerProductRequest, InnerProductResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ES2EService_InnerProductServer = grpc.ServerStreamingServer[InnerProductResponse]

func _ES2EService_BatchInsertData_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ES2EServiceServer).BatchInsertData(&grpc.GenericServerStream[BatchInsertDataRequest, BatchInsertDataResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ES2EService_BatchInsertDataServer = grpc.ClientStreamingServer[BatchInsertDataRequest, BatchInsertDataResponse]

func _ES2EService_CreateIndex_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ES2EServiceServer).CreateIndex(&grpc.GenericServerStream[CreateIndexRequest, CreateIndexResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ES2EService_CreateIndexServer = grpc.ClientStreamingServer[CreateIndexRequest, CreateIndexResponse]

func _ES2EService_GetKeyList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetKeyListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ES2EServiceServer).GetKeyList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ES2EService_GetKeyList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ES2EServiceServer).GetKeyList(ctx, req.(*GetKeyListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ES2EService_RegisterKey_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ES2EServiceServer).RegisterKey(&grpc.GenericServerStream[RegisterKeyRequest, RegisterKeyResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ES2EService_RegisterKeyServer = grpc.ClientStreamingServer[RegisterKeyRequest, RegisterKeyResponse]

func _ES2EService_LoadKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ES2EServiceServer).LoadKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ES2EService_LoadKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ES2EServiceServer).LoadKey(ctx, req.(*LoadKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ES2EService_UnloadKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnloadKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ES2EServiceServer).UnloadKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ES2EService_UnloadKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ES2EServiceServer).UnloadKey(ctx, req.(*UnloadKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ES2EService_DeleteKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ES2EServiceServer).DeleteKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ES2EService_DeleteKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ES2EServiceServer).DeleteKey(ctx, req.(*DeleteKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ES2EService_DeleteIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ES2EServiceServer).DeleteIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ES2EService_DeleteIndex_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ES2EServiceServer).DeleteIndex(ctx, req.(*DeleteIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ES2EService_ServiceDesc is the grpc.ServiceDesc for ES2EService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ES2EService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ES2E.ES2EService",
	HandlerType: (*ES2EServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "get_index_list",
			Handler:    _ES2EService_GetIndexList_Handler,
		},
		{
			MethodName: "get_metadata",
			Handler:    _ES2EService_GetMetadata_Handler,
		},
		{
			MethodName: "get_key_list",
			Handler:    _ES2EService_GetKeyList_Handler,
		},
		{
			MethodName: "load_key",
			Handler:    _ES2EService_LoadKey_Handler,
		},
		{
			MethodName: "unload_key",
			Handler:    _ES2EService_UnloadKey_Handler,
		},
		{
			MethodName: "delete_key",
			Handler:    _ES2EService_DeleteKey_Handler,
		},
		{
			MethodName: "delete_index",
			Handler:    _ES2EService_DeleteIndex_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "inner_product",
			Handler:       _ES2EService_InnerProduct_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "batch_insert_data",
			Handler:       _ES2EService_BatchInsertData_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "create_index",
			Handler:       _ES2EService_CreateIndex_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "register_key",
			Handler:       _ES2EService_RegisterKey_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "es2e/es2e-api.proto",
}
